--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
- !ruby/struct:SM::Flow::P 
  body: "@return &lt;Hash&gt;"
- !ruby/struct:SM::Flow::VERB 
  body: "  The configuration loaded from Merb.root / &quot;config/slices.yml&quot; or, if\n  the load fails, an empty hash.\n"
full_name: Merb::Slices::config
is_singleton: true
name: config
params: ()
visibility: public
