--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
- !ruby/struct:SM::Flow::P 
  body: ":api: plugin"
full_name: Merb::forking_environment?
is_singleton: true
name: forking_environment?
params: ()
visibility: public
