--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
- !ruby/struct:SM::Flow::P 
  body: Retrieve the value of a config entry, returning the provided default if the key is not present
- !ruby/struct:SM::Flow::H 
  level: 4
  text: Parameters
- !ruby/object:SM::Flow::LIST 
  contents: 
  - !ruby/struct:SM::Flow::LI 
    label: "key<Object>:"
    body: The key to retrieve the parameter for.
  - !ruby/struct:SM::Flow::LI 
    label: "default<Object>:"
    body: The default value to return if the parameter is not set.
  type: :NOTE
- !ruby/struct:SM::Flow::H 
  level: 4
  text: Returns
- !ruby/object:SM::Flow::LIST 
  contents: 
  - !ruby/struct:SM::Flow::LI 
    label: "Object:"
    body: The value of the configuration parameter or the default.
  type: :NOTE
- !ruby/struct:SM::Flow::P 
  body: ":api: public"
full_name: Merb::Config::fetch
is_singleton: true
name: fetch
params: (key, default)
visibility: public
