--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
- !ruby/struct:SM::Flow::P 
  body: Returns stores list constructed from configured session stores (:session_stores config option) or default one (:session_store config option).
- !ruby/struct:SM::Flow::P 
  body: ":api: private"
full_name: Merb::Config::session_stores
is_singleton: true
name: session_stores
params: ()
visibility: public
