--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
- !ruby/struct:SM::Flow::P 
  body: Returns the config as YAML.
- !ruby/struct:SM::Flow::H 
  level: 4
  text: Returns
- !ruby/object:SM::Flow::LIST 
  contents: 
  - !ruby/struct:SM::Flow::LI 
    label: "String:"
    body: The config as YAML.
  type: :NOTE
- !ruby/struct:SM::Flow::P 
  body: ":api: public"
full_name: Merb::Config::to_yaml
is_singleton: true
name: to_yaml
params: ()
visibility: public
