--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
- !ruby/struct:SM::Flow::P 
  body: "Evaluates the provided block, where any call to a method causes #[]= to be called on klass with the method name as the key and the arguments as the value."
- !ruby/struct:SM::Flow::H 
  level: 4
  text: Parameters
- !ruby/object:SM::Flow::LIST 
  contents: 
  - !ruby/struct:SM::Flow::LI 
    label: "klass<Object~[]=>:"
    body: The object on which to assign values.
  - !ruby/struct:SM::Flow::LI 
    label: "&block:"
    body: The block which specifies the config values to set.
  type: :NOTE
- !ruby/struct:SM::Flow::H 
  level: 4
  text: Returns
- !ruby/struct:SM::Flow::P 
  body: nil
- !ruby/struct:SM::Flow::P 
  body: ":api: private"
full_name: Merb::Config::ConfigBlock::new
is_singleton: true
name: new
params: (klass, &block)
visibility: public
