--- !ruby/object:RI::ClassDescription 
attributes: 
- !ruby/object:RI::Attribute 
  comment: 
  name: dyn
  rw: R
- !ruby/object:RI::Attribute 
  comment: 
  name: env
  rw: R
class_methods: 
- !ruby/object:RI::MethodSummary 
  name: new
comment: 
constants: []

full_name: RubyParser::Environment
includes: []

instance_methods: 
- !ruby/object:RI::MethodSummary 
  name: "[]"
- !ruby/object:RI::MethodSummary 
  name: "[]="
- !ruby/object:RI::MethodSummary 
  name: all
- !ruby/object:RI::MethodSummary 
  name: current
- !ruby/object:RI::MethodSummary 
  name: dynamic
- !ruby/object:RI::MethodSummary 
  name: dynamic?
- !ruby/object:RI::MethodSummary 
  name: extend
- !ruby/object:RI::MethodSummary 
  name: reset
- !ruby/object:RI::MethodSummary 
  name: unextend
- !ruby/object:RI::MethodSummary 
  name: use
- !ruby/object:RI::MethodSummary 
  name: used?
name: Environment
superclass: Object
